 <?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Model_pasien extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_pendaftaran by no_rekammedis
     */
    function get_tbl_pasien($no_rm)
    {
        $this->db->where('no_rm',$no_rm);
        return $this->db->get('tbl_pasien')->row();
    }
        
    /*
     * Get all tbl_pendaftaran
     */
    function get_all_tbl_pasien()
    {
        $this->db->order_by('no_rm', 'desc');
        return $this->db->get('tbl_pasien')->result_array();
    }
        
    /*
     * function to add new tbl_pendaftaran
     */
    function add_tbl_pasien($data)
    {
        $this->db->insert('tbl_pasien',$data);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_pendaftaran
     */
    function update_tbl_pasien($no_rm,$data)
    {
        $this->db->where('no_rm',$no_rm);
        return $this->db->update('tbl_pasien',$data);
    }
    
    /*
     * function to delete tbl_pendaftaran
     */
    function delete_tbl_pasien($no_rm)
    {
        return $this->db->delete('tbl_pasien',array('no_rm'=>$no_rm));
    }


    public function edit($no_rm)
    {

        $query = $this->db->where("no_rm", $no_rm)
                ->get("tbl_pasien");

        if($query){
            return $query->result_array();
        }else{
            return false;
        }

    }
}
